### ISSUE TITLE
TypeError: Cannot read property 'episodeFileCount' of undefined

### ISSUE THREAD

**Issue by mekarawr** [boban-bmw/cross-seedarr#3]
Fresh install. Radarr 3 works fine, Sonarr 3 does not

[1612800975127] INFO  (23092 on hostname): Fetching series...
[1612800976471] ERROR (23092 on hostname): An error occurred while processing series
    TypeError: Cannot read property 'episodeFileCount' of undefined
        at /root/cross-seedarr/sonarr.js:78:37
        at Array.filter (<anonymous>)
        at sonarrFlow (/root/cross-seedarr/sonarr.js:77:30)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async start (/root/cross-seedarr/index.js:28:5)

running version sonarr version 3.0.4.1107-ls51 by linuxserver.io

**Comment by boban-bmw** [comment]
Thanks for the bug report. Are you able to isolate which show this happens for?

**Comment by mekarawr** [comment]
sorry no this happens immediatly upon launching the script. is there some way i can make it do some sort of debug output or more verbose?

**Comment by mekarawr** [comment]
Hello again
I figured it out. I had some shows that had no episodes listed

Emergency Road Rescue
LAPD: Life on the Beat
Outback Paramedic

Deleting those from sonarr made the script work again. So problem solved! Thank you for you help.
